# configuration for vite.docs solidbase https://github.com/nikescar/ghaction-ghpage-solidbase-builder
# Site settings
title: Github Action Solidbase Builder
description: Solidbase Theme for markdown documents to site converter for GitHub Pages.
issue_link: "https://github.com/nikescar/ghaction-ghpage-solidbase-builder/issues"
edit_path: "https://github.com/nikescar/ghaction-ghpage-solidbase-builder/edit/main/:path"
lang: en
site_favicon: './resources/favicon.ico'
site_author: Woojae, Park
repo_url: 'https://github.com/nikescar/ghaction-ghpage-solidbase-builder'
site_url: 'http://nikescar.github.io/ghaction-ghpage-solidbase-builder/'

# 404 page redirection rules - for github site repo, ex. {id}.github.io
404_subsite_urls:
  - /ghaction-ghpage-solidbase-builder/
  # - /subpath/
  # - /subpath2/
  # - /github non-site repo/

# Excluded items can be re-enabled by adding them to the `include:` list.
exclude:
  - .github
  - .output
  - .vinxi
  - node_modules
  - scripts
  - tmp
  - _config.yml
  - app.config.ts
  - build.ts
  - package.json
  - package-lock.json
  - pnpm-lock.yaml
  - tsconfig.json

# Include in processing.
# The following items will be processed, even if they would otherwise be excluded.
include:
  - .well-known
  - index.md
  - docs
  - resources
  - README.md
  - CREDITS.md

# Theme settings
theme_upstream: 'https://github.com/nikescar/ghaction-ghpage-solidbase-builder'
theme_config:
  social_links:
    gitHub: 'https://github.com/nikescar/ghaction-ghpage-solidbase-builder'
    discord: 'https://discord.gg'
  nav:
    Docs: /ghaction-ghpage-solidbase-builder/docs
    Readme: /ghaction-ghpage-solidbase-builder/readme
    Credits: /ghaction-ghpage-solidbase-builder/credits
    # - Packages: /packages
    # - Blog: /blog
  sidebar:
    - Docs:
      - Guide:
          "Getting Started": /getting-started
          Features: /features
          Configuration: /configuration
          Deployment: /deployment

# locales:
#   kr:
#     label: 한국어
#     themeConfig:
#       nav:
#         -
#           text: 가이드
#           link: /guide
#         -
#           text: 참조
#           link: /Reference
#       sidebar:
#         "/guide":
#           -
#             title: 가이드
#             collapsed: false
#             items:
#               -
#                 title: "시작하기"
#                 link: "/getting-started"
#               -
#                 title: "기능목록"
#                 link: "/features"
#               -
#                 title: "설정"
#                 link: "/configuration"
#               -
#                 title: "배포"
#                 link: "/deployment"
#         "/reference":
#           -
#             title: 참조
#             collapsed: false
#             items:
