# configuration for vite.docs solidbase https://github.com/nikescar/mdx-sitegen-solidbase
# Site settings
title: Github Action Solidbase Builder
description: Solidbase Theme for markdown documents to site converter for GitHub Pages.
issue_link: "https://github.com/nikescar/mdx-sitegen-solidbase/issues"
edit_path: "https://github.com/nikescar/mdx-sitegen-solidbase/edit/main/:path"
lang: en
site_favicon: './resources/favicon.ico'
site_author: Woojae, Park
repo_url: 'https://github.com/nikescar/mdx-sitegen-solidbase'
site_url: 'http://nikescar.github.io/mdx-sitegen-solidbase/'

# 404 page redirection rules - for github site repo, ex. {id}.github.io
404_subsite_urls:
  - /mdx-sitegen-solidbase/
  # - /subpath/
  # - /subpath2/
  # - /github non-site repo/

# Excluded items can be re-enabled by adding them to the `include:` list.
exclude:
  - .secrets
  - .github
  - .output
  - .vinxi
  - .solidbase
  - .git
  - .gitignore
  - node_modules
  - scripts
  - tmp
  - _config.yml
  - app.config.ts
  - package.json
  - package-lock.json
  - pnpm-lock.yaml
  - tsconfig.json

# Include in processing.
# The following items will be processed, even if they would otherwise be excluded.
include:
  - .well-known
  - index.md
  - docs
  - resources
  - README.md
  - CREDITS.md

# Theme settings
theme_upstream: 'https://github.com/nikescar/mdx-sitegen-solidbase'
theme_config:
  social_links:
    gitHub: 'https://github.com/nikescar/mdx-sitegen-solidbase'
    discord: 'https://discord.gg'
  nav:
    Docs: /mdx-sitegen-solidbase/docs
    Readme: /mdx-sitegen-solidbase/readme
    Credits: /mdx-sitegen-solidbase/credits
    # - Packages: /packages
    # - Blog: /blog
  sidebar:
    - Docs:
      - Guide:
          "Getting Started": /getting-started
          Features: /features
          Configuration: /configuration
          Deployment: /deployment

# gitHub pages deployment(gh-pages.publish) settings # https://github.com/new
# 1. Create a GitHub repository
# 2. Enable GitHub Pages in the repository settings
# 3. Generate a personal access token with "repo" and "workflow" scopes and save it as GITHUB_TOKEN secret in your GitHub repository
deployment: # https://github.com/settings/personal-access-tokens
  provider: 'github-page'
  github_token: ${{ secrets.GITHUB_TOKEN }}
  github_repo: 'nikescar/mdx-sitegen-solidbase'

# deno deploy(deployctl) settings # https://dash.deno.com/new_project
# 1. Create a Deno Deploy project
# 2. Generate a Deno Deploy token and save it as DENO_DEPLOY_TOKEN secret in your GitHub repository
# deployment: # https://dash.deno.com/account#access-tokens
#   provider: 'deno-deploy'
#   project: 'mdx-sitegen-solidbase'
#   deno_deploy_token: ${{ secrets.DENO_DEPLOY_TOKEN }} 

# firebase deploy(firebase) settings # https://console.firebase.google.com/u/0/
# 1. Create a Firebase project
# 2. Create a service account with the "Firebase Admin SDK" role
# 3. Generate a private json key for the service account and save it as FIREBASE_SERVICE_ACCOUNT_KEY secret in your GitHub repository
# deployment: # https://console.cloud.google.com/projectselector2/iam-admin/serviceaccounts?authuser=0&supportedpurview=project
#   provider: 'firebase'
#   project: 'mdx-sitegen-solidbase'
#   service_account_key_text: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}
