# configuration for vite.docs solidbase https://github.com/nikescar/jekyll-theme-solidbase
# Site settings
title: Jekyll Solidbase Theme
description: Solidbase Theme to Jekyll to use with GitHub Pages.
show_downloads: true

# Excluded items can be re-enabled by adding them to the `include:` list.
exclude:
  - _includes
  - _layouts
  - .github
  - .output
  - .vinxi
  - node_modules
  - scripts
  - tmp
  - _config.yml
  - _config.jekyll.yml
  - app.config.ts
  - build.ts
  - Gemfile
  - Gemfile.lock
  - package.json
  - package-lock.json
  - pnpm-lock.yaml
  - tsconfig.json

# Include in processing.
# The following items will be processed, even if they would otherwise be excluded.
include:
  - .well-known
  - index.md
  - docs
  - resources
  - README.md
  - CREDITS.md

# Theme settings
site_author: Woojae, Park
repo_url: 'https://github.com/nikescar/jekyll-theme-solidbase'
# site_url does not support subpaths, so it should be the root URL of your site.
site_url: 'http://nikescar.github.io/ghaction-ghpage-solidbase-builder/'
# edit_on_github: true
# github_docs_folder: false
# sticky_navigation: true
# search_enabled: false
# logo: 'https://your.url/image.png'
site_favicon: './resources/favicon.ico'

theme_settings:
  social_links:
    GitHub: 'https://github.com/nikescar/jekyll-theme-solidbase'
  en:
    title: Jekyll Solidbase Theme
    lang: en
    nav:
      Docs: /docs
      Readme: /readme
      Credits: /credits
      # - Packages: /packages
      # - Blog: /blog
    sidebar:
      - Docs:
        - Guide:
            "Getting Started": /getting-started
            Features: /features
            Configuration: /configuration
            Deployment: /deployment
