# USAGE
# - name: Build with Solidbase Theme
#   uses: ./.github/actions/solidbase-theme
#   with:
#     config_path: '_config.yml'
#   env:
#     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

name: 'Build with Solidbase Theme'
description: 'A GitHub Action to download and build with Solidbase theme'
author: 'GitHub'
runs:
  using: 'composite'
  steps:
    - name: Download and build with theme
      shell: bash
      run: |
        export theme_upstream=$(grep -m1 'theme_upstream:' ${{ inputs.config_path }} | awk '{print $2}' | sed "s/'//g")/archive/refs/heads/main.tar.gz
        wget -q "$theme_upstream" -O main.tar.gz
        if [ $? -ne 0 ]; then
            echo "Failed to download theme from $theme_upstream"
            exit 1
        fi
        mkdir -p .solidbase
        tar -xzf main.tar.gz --strip-components=1 -C .solidbase
        pushd ./.solidbase
        bash ghworkflow.sh
        popd
inputs:
  config_path:
    description: 'Path to _config.yml file'
    required: false
    default: '_config.yml'

